version: '3.8'

services:
  loglama:
    build:
      context: ../..
      dockerfile: examples/loglama-grafana/Dockerfile
    image: loglama-local:latest
    container_name: loglama
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/logs
      - ./pylama.env:/app/.env  # Example env file if needed
    environment:
      - LOGLAMA_LOG_DIR=/logs
      - LOGLAMA_CONSOLE_ENABLED=true
      - LOGLAMA_SQLITE_ENABLED=true
    depends_on:
      - grafana

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped

volumes:
  grafana-data:
